### ISSUE TITLE
Please rename project - There is already NeptuneOS which is a Linux distro

### ISSUE THREAD

**Issue by llelectronics** [cl91/NeptuneOS#5] opened 2022-03-01 08:54 UTC
More than a decade ago we started the linux distribution and called it NeptuneOS. It got a bit of fame and is known amongst Linux users. 
You can find our distro on https://neptuneos.com 
I think you see the issue we have now. We use the same name for totally different projects. 

I sincerely ask you to overthink you projects name and come up with something different.

**Comment by Hueristic** [comment] 2022-03-01 16:08
I knew this sounded familiar.

**Comment by pinaraf** [comment] 2022-03-04 13:55
This is a duplicate of #1 that was rejected a few days ago, so I think the project owner will close it too.

**Comment by cl91** [comment] 2022-03-05 01:53
I mean this is just a personal hobbyist project so having a name conflict is unlikely going to be a problem. In the unlikely event that this got popular I'll maybe think of something else. For the moment I'll keep it. The main reason I like the name is because I can use the shorthand 'ntos' to stand for 'NeptuneOS' instead of a Microsoft trademark.

**Closed** 2022-06-13 03:21 UTC
